### ISSUE TITLE
Extra Vivado options

### ISSUE THREAD

**Issue by gmartin102** [olofk/edalize#241]
This maybe not the correct place for this issue/question, but maybe someone can point me in the correct direction.  I am working with openhwgroup on an SoC that is using fusesoc to build fpga based emulation hardware.  All is working ok, except the vivado tools are using the flatten-hierarchy=rebuilt option and I would like to have it be flatten_hierarchy=none.  I've tried a couple of  things but no luck on getting it to actually do what i want.  how should I add tcl command options for vivado to use in the synthesis?  the following is a snip from my core file.

```
 nexys-a7-100t:
    <<: *default
    default_tool: vivado
    description: Digilent Nexys-A7-100T Board
    parameters:
    - PULP_FPGA_EMUL=true
    - flatten_hierarchy=none
    filesets_append:
    - nexys-cfg
    - nexys-xdc
    tools:
      vivado:
        part: xc7a100tcsg324-1
        flatten_hierarchy: none
    toplevel: xilinx_core_v_mcu
```
