### ISSUE TITLE
How to use custom Tcl procedure in Vivado?

### ISSUE THREAD

**Issue by sjalloq** [olofk/edalize#286]
I'm using the Vivado Tcl hook scripts in my flow (taken from the OpenTitan examples) but I've been trying to write some common Tcl procedures that I would like to call from those hook scripts.  For example, I'm running on a cluster where I need to know how many CPU slots I've been granted.  I've got the following proc defined in a file called vivado_common.tcl:

```tcl
proc ::get_available_slots {} {
  # Returns the number of slots available on an SGE host.  If the $NSLOTS
  # environment variable isn't present, then we assume that we are running
  # on a local host where we can use all CPUs.  Vivado can use upto 8 for
  # parallel runs so that is the maximum value returned.

  if { [info exists $::env(NSLOTS)] } {
    return $::env(NSLOTS)
  } else {
    return 8
  }
}
```

and I was adding this to my run by declaring it as a `tclSource` file in my core file:

```yaml
  files_tcl:
    files:
      - tcl/vivado_common.tcl: {file_type: tclSource}
      - tcl/vivado_setup_hooks.tcl: {file_type: tclSource}
      # The following hook files are copied to the fusesoc workroot. They are referenced from
      # the vivado_setup_hooks.tcl script.  See UG894, Defining Tcl Hook Scripts.
      - tcl/vivado_hook_synth_design_pre.tcl: {file_type: user, copyto: vivado_hook_synth_design_pre.tcl}
      - tcl/vivado_hook_synth_design_post.tcl: {file_type: user, copyto: vivado_hook_synth_design_post.tcl}
      - tcl/vivado_hook_synth_design_post.tcl: {file_type: user, copyto: vivado_hook_route_design_post.tcl}
```

This doesn't seem to work and I get an error when sourcing the relevant hook script that the proc doesn't exist.  I think this is due to the way the Vivado Makefile runs the tool.  It seems to run a Tcl script that creates the project file and then launches a second instance of Vivado to run the project.  Any `tclSource` file is only sourced by the setup script and isn't passed to the full project run.

Is that correct?  What is the best way to declare procs to use in a hook script?  Do I just need to add it as a `user` file type and manually source it from the relevant hook script?
